'use client'
import styled from "styled-components"
import Link from "next/link"
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

/*export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
  */
export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        
      <Navbar>
<Linkto href="/">홈</Linkto>
<Linkto href="/list">List</Linkto>
<Linkto href="/cart">Cart</Linkto>

       </Navbar>
        {children}</body>
    </html>
  );
}


//page.js를 보여줄때 layout.js안에 담아서 보여주기 때문에
// Navbar가 모든 항목에 퍼져있는 것
const Navbar=styled.div`
display: flex;
flex-direction: row;
width: 100%;

background-color: white;

gap: 20px;


`
const Linkto= styled(Link)`
padding: 20px;
text-decoration: none;
color: blue;

`